version: "3.8"

services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nubichallenge
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: fastapi
    volumes:
      - .:/app
      - ./data:/var/lib/postgresql/data
    environment:
      PGSQL_HOST: "postgres"
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  data:

